#ifndef _TIMERS_CONFIG_H_
#define _TIMERS_CONFIG_H_

#define  CPU_CLOCK_FREQ		_8MHz
#define  TIMER0_ENABLE 		ENABLE
#define  TIMER1_ENABLE 		DISABLE
#define  TIMER2_ENABLE 		DISABLE

#define  TIMER0_PRESCALER	DIV_BY_64


#define TIMER0_INTERRUPT_ENABLE		ENABLE
#define TIMER1_INTERRUPT_ENABLE 	DISABLE


#define TIMER0_OCI_ENABLE			ENABLE


#define	TIMER0_MODE				CTC
#define OCR0_INIT				125

#define COMPARE_OUTPUT_MODE		SET_ON_TOP

#endif
